config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pages do
  	resources :rows, shallow: true do
  		member do
  			get :toggle_mobile
  			get :toggle_tablet
  			get :toggle_laptop
  			get :toggle_desktop
  			get :toggle_all_devices
  		end
  	end
  end
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

	#associations
	has_many :rows
	#callbacks
	before_update :parameterize_slug
	before_update :calculate_slug, if: :uniqness_slug

	def parameterize_slug
		self.slug.parameterize
	end

	def uniqness_slug?
		#self.slug.uniqness?
	end

	def calculate_slug
		number = self.slug.to_i
		if number > 0
			sulg << '_#{number + 1}'
		else
			slug << '_#{}'
		end
	end
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :page

  before_create :set_null_html_class

  #before_save :hide_mobile?, :toggle_mobile

  def hide_mobile_icon
  	 if self.html_class.to_s.include? 'hide-on-small-only' 
      'grey-text'
     else
      'white-text'
    end
  end

  def hide_tablet_icon
     if self.html_class.to_s.include? 'hide-on-med-only' 
      'grey-text'
     else
      'white-text'
    end
  end

  def hide_laptop_icon
     if self.html_class.to_s.include? 'hide-on-large-only' 
      'grey-text'
     else
      'white-text'
    end
  end

  def hide_desktop_icon
     if self.html_class.to_s.include? 'hide-on-extra-large-only' 
      'grey-text'
     else
      'white-text'
    end
  end

  def hide_all_devices_icon
    #puts ['hide-on-extra-large-only', 'hide-on-large-only','hide-on-med-only', 'hide-on-small-only'].include? self.html_class.to_s
    # if self.html_class.to_s.include?( 'hide-on-extra-large-only' && 'hide-on-large-only' && 'hide-on-med-only' && 'hide-on-small-only')
    #    'grey-text'
    # else
    #  'white-text'
    #end
  end

  def self.toggle_mobile(row)
    unless row.html_class.to_s.include? 'hide-on-small-only'
      row.html_class << ' hide-on-small-only' 
    else
  	 row.html_class.slice! 'hide-on-small-only'
     #row.html_class.to_s.delete '-'
    end
    row.save!
  end

  def self.toggle_tablet(row)
    unless row.html_class.to_s.include? 'hide-on-med-only'
      row.html_class << ' hide-on-med-only' 
    else
     row.html_class.slice! 'hide-on-med-only'
     #row.html_class.to_s.delete '-'
    end
    row.save!
  end

  def self.toggle_laptop(row)
    unless row.html_class.to_s.include? 'hide-on-large-only'
      row.html_class << ' hide-on-large-only' 
    else
     row.html_class.slice! 'hide-on-large-only'
     #row.html_class.to_s.delete '-'
    end
    row.save!
  end

  def self.toggle_desktop(row)
    unless row.html_class.to_s.include? 'hide-on-extra-large-only'
      row.html_class << ' hide-on-extra-large-only' 
    else
     row.html_class.slice! 'hide-on-extra-large-only'
     #row.html_class.to_s.delete '-'
    end
    row.save!
  end

  def self.toggle_all_devices(row)
    #puts row.html_class.to_s
    puts  row.html_class.to_s.include?( 'hide-on-extra-large-only' || 'hide-on-large-only' || 'hide-on-med-only' || 'hide-on-small-only')
    #puts 'hide-on-extra-large-only'.include? row.html_class.to_s
    unless row.html_class.to_s.include?( 'hide-on-extra-large-only' || 'hide-on-large-only' || 'hide-on-med-only' || 'hide-on-small-only')
      row.html_class << ' hide-on-small-only' 
      row.html_class << ' hide-on-med-only' 
      row.html_class << ' hide-on-large-only' 
      row.html_class << ' hide-on-extra-large-only' 
    else
     row.html_class.slice! 'hide-on-small-only'
     row.html_class.slice! 'hide-on-med-only'
     row.html_class.slice! 'hide-on-large-only'
     row.html_class.slice! 'hide-on-extra-large-only'
    end
    row.save!
  end

  def set_null_html_class
  	self.html_class ||= ''
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_action :set_page, only: [:edit, :show]

	def index
		@pages = Page.all
		#@page = Page.create(draft:true)
	end

	def new
		#@page = Page.new
	end

	def create
		@page = Page.create(draft:true)
		redirect_to edit_page_path(@page)
	end

	def edit
		#@page = Page.find(params[:id])
	end

	def update
	end

	def show
		@page = Page.find_by(slug: params[:slug])
	end

	def delete
	end

	private

	def set_page
		@page = Page.includes(:rows).find(params[:id])
	end

	def page_params

	end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController

	before_action :set_page, only: [:index, :create]
	before_action :set_row, only: [
	:hide_mobile,
	:toggle_mobile,
	:toggle_tablet,
	:toggle_laptop,
	:toggle_desktop,
	:toggle_all_devices]

	def index
		
	end

	def new; end

	def create
		@row = @page.rows.create

		respond_to do |format|

			format.html { redirect_to edit_page_path(@row.page) }
			format.js
		end
	end

	def edit
		#@page = Page.find(params[:id])
	end

	def update
	end

	def show
		@page = Page.find_by(slug: params[:slug])
	end

	def delete
	end

	def toggle_mobile
		Row.toggle_mobile(@row)
		@page = @row.page
		respond_to do |format|

			format.html {@row}
			format.js
		end
  		
	end

	def toggle_tablet
		Row.toggle_tablet(@row)
		@page = @row.page
		respond_to do |format|

			format.html {@row}
			format.js
		end
  		
	end

	def toggle_laptop
		Row.toggle_laptop(@row)
		@page = @row.page
		respond_to do |format|

			format.html {@row}
			format.js
		end
  		
	end

	def toggle_desktop
		Row.toggle_desktop(@row)
		@page = @row.page
		respond_to do |format|

			format.html {@row}
			format.js
		end
  		
	end

	def toggle_all_devices
		Row.toggle_all_devices(@row)
		@page = @row.page
		respond_to do |format|

			format.html {@row}
			format.js
		end
  		
	end

	private

	def set_row
		@row = Row.find(params[:id])
	end

	def set_page
		@page = Page.find(params[:page_id])
	end

	def row_params

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rows_helper.rb
module RowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnterSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_page.html.erb
<div id="page_area" class="blue-grey lighten-5">
<div class="nav-wrapper blue-grey darken-1">
      <div class="col s12  valign-wrapper-">
        <a href="#!" class="breadcrumb">Home</a>
       <%= link_to pages_path, class: "breadcrumb" do %>Strony<% end %>
        <a href="#!" class="breadcrumb">Nowa strona</a>
      </div>
    </div>
<div class="row valign-wrapper">
	<div class="col s12 m6 left">
		<h1>Nowa strona</h1>        
	</div>
	<div class="col s12 m6">
		<%= link_to new_page_path(@page), class: 'btn btn-large right' do %>
			<i class="material-icons left">save</i> Zapisz
		<% end %>
	</div>

	


</div>


	<div class="row white">
		<div class="page_section">Wygląd w wyszukiwarce</div>
		<div class="input-field row col s4">
			<div class="title">Nowa strona
				<% text_field_tag 'name', params[nil], class: 'title character_counter', data: {length: '60'} %>
			</div>
			<br><div class="url">
			<span>
				<%= root_url.to_s %>nowa-strona
				<% text_field_tag 'name2', params[nil], class: 'url' %></span>
			</div>
			<div class="description">
			Opis strony to jest sobie taki opis
			</div>
		</div>

		

	   
</div>
<div class="page_section">Treść</div>




<div class="site-wrapper">

  <section class="topbar">
    <article class="brand">
      Treść
    </article>

    <div class="navbar-right">  
        <ul class="device-chooser">
          <li class="device-size"></li>
        </ul>
      </article>
    </div>
  </section>

  <section class="content">
    <article>
      <div class="device-wrapper">
        <div id="screen" style="overflow-y: auto;">
        	<% unless @page.rows.any? %>
			  <div id="need_rows" class="center-align blue-grey lighten-3">
			  		&nbsp;
			  		<h3>Nie masz jeszcze żadnego wiersza na stronie.</h3> <h5>Wiersze ułatwiają układanie treści.</h5><br>
			  		<%= link_to page_rows_path(@page.id), method: :post, id: "new_link", class: "btn-floating btn-large waves-effect waves-light blue-grey darken-4 pulse", remote: true do %>
			  		<i class="material-icons white-text">add</i>

			  		<% end %><br>&nbsp;
			  		
				  		<div class="header grey darken-1 white-text add_row" style="padding:10px; width:90%; margin: 0 auto;  ">
						<i class="material-icons white-text left">add</i> Dodaj pierwszy wiersz
						</div>
					

			  </div>
			<% end %>

		  	<div id="rows_area" class="area grey lighten-3 ">
			<%= render @page.rows %>



			</div>

			<% if @page.rows.any? %>  
			   <div id="add_rows" class="center-align blue-grey- lighten-3-">
				<%= link_to page_rows_path(@page.id), method: :post, remote: true, id: "new_link", class: "btn-floating btn-large waves-effect waves-light blue-grey darken-4" do %>
			  		<i class="material-icons white-text">add</i>

			  		<% end %>
			  	</div>
			  	<div class="header grey- darken-1- white-text add_row" style="padding:10px; width:90%; margin: 0 auto;  ">
						<i class="material-icons white-text left">add</i> Dodaj pierwszy wiersz
						</div>
			<% end %>
        </div>
      </div>
    </article>
  </section>


</div>

app/views/pages/edit.html.erb
<div id="page">
<%= render 'page' %>
</div>

app/views/pages/index.html.erb
<div class="nav-wrapper ">
      <div class="col s12 grey-text grey valign-wrapper-">
        <a href="#!" class="breadcrumb">Home</a>
        <a href="#!" class="breadcrumb">Strony</a>
      </div>
</div>
<div class="row valign-wrapper">
	<div class="col s12 m6 left">
		<h1>Strony</h1>        
	</div>
	<div class="col s12 m6">
		<%= link_to(pages_path, method: :post, class: 'btn btn-large right') do %>
			<i class="material-icons left">add</i> Dodaj stronę
		<% end %>
	</div>
</div>

<div class="row">
	<% @pages.each do |page| %>
		<%= page.id %><br>
	<% end %>

</div>

app/views/pages/new.html.erb
<div class="nav-wrapper blue-grey darken-1">
      <div class="col s12  valign-wrapper-">
        <a href="#!" class="breadcrumb">Home</a>
       <%= link_to pages_path, class: "breadcrumb" do %>Strony<% end %>
        <a href="#!" class="breadcrumb">Nowa strona</a>
      </div>
    </div>
<div class="row valign-wrapper">
	<div class="col s12 m6 left">
		<h1>Nowa strona</h1>        
	</div>
	<div class="col s12 m6">
		<%= link_to new_page_path(@page), class: 'btn btn-large right' do %>
			<i class="material-icons left">save</i> Zapisz
		<% end %>
	</div>

	


</div>
	<div class="row">
		<div class="input-field row col s4">
			<div class="">
				<%= text_field_tag 'name', params[nil], class: 'title character_counter', data: {length: '60'} %>
			</div>
			<div class="url">
			<span><% root_url.to_s %>
				<%= root_url.to_s %>
				<%= text_field_tag 'name2', params[nil], class: 'url' %></span>
			</div>
			<div class="description">
			Opis strony to jest sobie taki opis
			</div>
		</div>

		<div class="row">
	      <form class="col s12">
	        <div class="row">
	          <div class="input-field col s6">
	            <input id="input_text" class="character_counter title" type="text" data-length="10">
	            <label for="input_text">Input text</label>
	          </div>
	        </div>
	        <div class="row">
	          <div class="input-field col s12">
	            <textarea id="textarea2" class="materialize-textarea" data-length="120"></textarea>
	            <label for="textarea2">Textarea</label>
	          </div>
	        </div>
	      </form>
	    </div>

	    <a class="btn tooltipped" data-position="bottom" data-tooltip="I am a tooltip">Hover me!</a>
	</div>

app/views/rows/_row.html.erb
<div class="hoverable" id="row_<%=row.id%>" style="margin-bottom:10px;" > 
	<div class="header grey darken-1 white-text" style="padding:10px; ">
		Wiersz <%= row.id %>
		<div class="left" style="overwflow:hidden; line-height:15px;">
			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text" style="cursor:grab;">drag_handle</i>
			<% end %>|

			<%= link_to toggle_all_devices_row_path(row), class: "", remote: true do %>
				<i class="material-icons small <%=row.hide_all_devices_icon%>">phonelink</i>
			<% end %>
			
			<%= link_to toggle_mobile_row_path(row), class: "", remote: true do %>
				<i class="material-icons small <%=row.hide_mobile_icon%>">phone_iphone</i>
			<% end %>
			<%= link_to toggle_tablet_row_path(row), class: "", remote: true do %>
				<i class="material-icons small <%=row.hide_tablet_icon%>">tablet_mac</i>
			<% end %>
			<%= link_to toggle_laptop_row_path(row), class: "", remote: true do %>
				<i class="material-icons small <%=row.hide_laptop_icon%>">laptop_mac</i>
			<% end %>
			<%= link_to toggle_desktop_row_path(row), class: "", remote: true do %>
				<i class="material-icons small <%=row.hide_desktop_icon%>">desktop_windows</i>
			<% end %>|
			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">lens</i>
			<% end %>
			

			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">format_color_text</i>
			<% end %>|
			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">vertical_align_center</i>
			<% end %>
			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">format_align_left</i>
			<% end %>

	
		</div>

		<div class="right" style="overwflow:hidden; line-height:15px;">
			

			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">settings</i>
			<% end %>

			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">view_agenda</i>
			<% end %>

			<%= link_to '#', class: "", remote: true do %>
				<i class="material-icons small white-text">delete</i>
			<% end %>
			<br>
	    </div>
	</div>
	<div class="content white row <%=row.html_class%>">
		<div class="blue col s12"><%= row.html_class %></div>
	</div>
</div>

app/views/rows/create.js.erb
//rwdscreen();
//alert('hello');
$('#need_rows').hide('slow');
//$('#page').find('#page_area').remove()
$('#page_area').replaceWith('<%= j render @row.page %>');
//$('#rows_area').append('<%= j render @row %>')
//$('#row_<=row.id%>').slideDown( "slow" );

rwdscreen();

app/views/rows/toggle_all_devices.js.erb
$('#row_<%=@row.id%>').replaceWith('<%= j render @row %>');

app/views/rows/toggle_desktop.js.erb
$('#row_<%=@row.id%>').replaceWith('<%= j render @row %>');

app/views/rows/toggle_laptop.js.erb
$('#row_<%=@row.id%>').replaceWith('<%= j render @row %>');

app/views/rows/toggle_mobile.js.erb
//rwdscreen();
//alert('hello');
//$('#need_rows').hide('slow');
//$('#page').find('#page_area').remove()
//$('#page_area').replaceWith('<%= j render @row.page %>');
//$('#rows_area').append('<%= j render @row %>')
//$('#row_<=@row.id%>').replaceWith('<%= j render @row %>');
$('#row_<%=@row.id%>').replaceWith('<%= j render @row %>');
//$('#row_<%=@row.id%>').append('HELLO WORLD')
//rwdscreen();

app/views/rows/toggle_tablet.js.erb
$('#row_<%=@row.id%>').replaceWith('<%= j render @row %>');